
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-proyecto
  labels:
    app: node
  namespace: mi-proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: us.gcr.io/proyectogchome/serverclonestackoverflow
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: vol
            mountPath: /usr/src/app/uploads
      volumes:
        - name: vol
          persistentVolumeClaim:
            claimName: pvc-uploads-1
    
---

apiVersion: v1
kind: Service
metadata:
  name: servicio-back-proyecto
  namespace: mi-proyecto 
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP